// <auto-generated />
using Havenza.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Havenza.Infrastructure.Migrations
{
    [DbContext(typeof(HavenzaDbContext))]
    [Migration("20251106162940_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Havenza.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Decor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lighting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Textiles"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Living Decor"
                        });
                });

            modelBuilder.Entity("Havenza.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A timeless three-seater sofa with a solid walnut base and linen-blend fabric. Perfect for modern living rooms.",
                            ImageUrl = "https://placehold.co/600x400/E2A16F/FFF?text=Walnut+Sofa",
                            Name = "Mid-Century Walnut Sofa",
                            Price = 1299.99,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Compact 4-seater dining table with a genuine white marble top and sleek black metal legs.",
                            ImageUrl = "https://placehold.co/600x400/E2A16F/FFF?text=Marble+Table",
                            Name = "Round Marble Dining Table",
                            Price = 749.5,
                            Stock = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Queen-sized bed with a high, tufted headboard, upholstered in a light beige, durable linen fabric.",
                            ImageUrl = "https://placehold.co/600x400/E2A16F/FFF?text=Linen+Bed",
                            Name = "Linen Upholstered Bed Frame",
                            Price = 899.0,
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Simple and robust writing desk with two drawers, designed for a clean and focused workspace.",
                            ImageUrl = "https://placehold.co/600x400/E2A16F/FFF?text=Office+Desk",
                            Name = "Minimalist Office Desk",
                            Price = 345.99000000000001,
                            Stock = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Versatile storage unit with adjustable shelves, finished in a matte dark gray lacquer.",
                            ImageUrl = "https://placehold.co/600x400/E2A16F/FFF?text=Storage+Cabinet",
                            Name = "Modular Storage Cabinet",
                            Price = 520.0,
                            Stock = 6
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Large, hand-painted abstract canvas piece with muted blue and warm tan tones.",
                            ImageUrl = "https://placehold.co/600x400/86B0BD/FFF?text=Abstract+Art",
                            Name = "Abstract Canvas Wall Art",
                            Price = 119.98999999999999,
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Full-length standing mirror with a thin, brass-finished curved metal frame.",
                            ImageUrl = "https://placehold.co/600x400/86B0BD/FFF?text=Floor+Mirror",
                            Name = "Curved Metal Floor Mirror",
                            Price = 185.0,
                            Stock = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "A collection of five mixed-size frames (3x5, 4x6, 5x7) with natural oak finish and shatter-proof glass. Perfect for creating a gallery wall.",
                            ImageUrl = "https://placehold.co/600x400/86B0BD/FFF?text=Sculptures",
                            Name = "Set of 5 Minimalist Photo Frames",
                            Price = 45.990000000000002,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Silent wall clock featuring an unfinished wood face and simple black hands.",
                            ImageUrl = "https://placehold.co/600x400/86B0BD/FFF?text=Wood+Clock",
                            Name = "Minimalist Wooden Clock",
                            Price = 59.5,
                            Stock = 18
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Hand-blown glass vase with a subtle transparent texture, perfect for fresh flowers or as a standalone piece.",
                            ImageUrl = "https://placehold.co/600x400/86B0BD/FFF?text=Glass+Vase",
                            Name = "Transparent Glass Vase",
                            Price = 35.0,
                            Stock = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Single-bulb ceiling pendant with a matte black metal cage design, adjustable cord length.",
                            ImageUrl = "https://placehold.co/600x400/2C2C2C/FFF?text=Pendant+Light",
                            Name = "Industrial Black Pendant Light",
                            Price = 95.0,
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "A classic table lamp featuring a solid brass base and a soft, white linen drum shade.",
                            ImageUrl = "https://placehold.co/600x400/2C2C2C/FFF?text=Table+Lamp",
                            Name = "Brass & Linen Table Lamp",
                            Price = 65.989999999999995,
                            Stock = 15
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Tall, arched floor lamp designed to hang over a sofa or chair for optimal reading light.",
                            ImageUrl = "https://placehold.co/600x400/2C2C2C/FFF?text=Floor+Lamp",
                            Name = "Arched Reading Floor Lamp",
                            Price = 130.0,
                            Stock = 9
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Under-cabinet or shelf-mounted LED light strip for subtle accent illumination.",
                            ImageUrl = "https://placehold.co/600x400/2C2C2C/FFF?text=LED+Strip",
                            Name = "Minimalist LED Strip Light",
                            Price = 45.0,
                            Stock = 25
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Elegant chandelier with cascading crystal clusters, perfect for dining rooms or entryways.",
                            ImageUrl = "https://placehold.co/600x400/2C2C2C/FFF?text=Chandelier",
                            Name = "Crystal Cluster Chandelier",
                            Price = 499.99000000000001,
                            Stock = 4
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Large area rug made of ethically sourced wool with a subtle geometric pattern in neutral tones.",
                            ImageUrl = "https://placehold.co/600x400/FFF0DD/2C2C2C?text=Wool+Rug",
                            Name = "Hand-Woven Wool Rug (8'x10')",
                            Price = 399.0,
                            Stock = 7
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Ultra-soft acrylic throw blanket with a thick, chunky knit texture, perfect for cozy evenings.",
                            ImageUrl = "https://placehold.co/600x400/FFF0DD/2C2C2C?text=Knit+Throw",
                            Name = "Chunky Knit Throw Blanket",
                            Price = 85.0,
                            Stock = 22
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Pair of luxurious velvet cushion covers (18x18 inches) in a deep forest green.",
                            ImageUrl = "https://placehold.co/600x400/FFF0DD/2C2C2C?text=Velvet+Cushions",
                            Name = "Set of 2 Velvet Cushion Covers",
                            Price = 29.989999999999998,
                            Stock = 35
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Single panel linen curtains with a full blackout lining, 84 inches long.",
                            ImageUrl = "https://placehold.co/600x400/FFF0DD/2C2C2C?text=Linen+Curtains",
                            Name = "Blackout Linen Curtains",
                            Price = 55.0,
                            Stock = 14
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Queen size duvet cover and sham set made from ultra-soft 600-thread count Egyptian cotton.",
                            ImageUrl = "https://placehold.co/600x400/FFF0DD/2C2C2C?text=Duvet+Set",
                            Name = "Egyptian Cotton Duvet Cover Set",
                            Price = 110.0,
                            Stock = 11
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "A realistic, high-quality faux fiddle-leaf fig tree (6 ft tall), perfect for low-light spaces.",
                            ImageUrl = "https://placehold.co/600x400/D1D3D4/2C2C2C?text=Fiddle+Leaf",
                            Name = "Large Fiddle-Leaf Fig (Faux)",
                            Price = 159.99000000000001,
                            Stock = 9
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Modern white ceramic planter with a geometric diamond texture, suitable for 6-inch plants.",
                            ImageUrl = "https://placehold.co/600x400/D1D3D4/2C2C2C?text=Planter",
                            Name = "Geometric Ceramic Planter",
                            Price = 29.0,
                            Stock = 40
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Hand-knotted macrame hanger made from natural cotton rope for small to medium pots.",
                            ImageUrl = "https://placehold.co/600x400/D1D3D4/2C2C2C?text=Macrame",
                            Name = "Hanging Macrame Plant Holder",
                            Price = 19.5,
                            Stock = 50
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "Low-maintenance succulent gardens in glass terrariums.",
                            ImageUrl = "https://placehold.co/600x400/D1D3D4/2C2C2C?text=Terrariums",
                            Name = "Succulent Terrariums",
                            Price = 75.0,
                            Stock = 18
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Sleek, black powder-coated metal stand, elevating plants to better catch light.",
                            ImageUrl = "https://placehold.co/600x400/D1D3D4/2C2C2C?text=Plant+Stand",
                            Name = "Tall Metal Plant Stand",
                            Price = 49.990000000000002,
                            Stock = 16
                        });
                });

            modelBuilder.Entity("Havenza.Core.Entities.Product", b =>
                {
                    b.HasOne("Havenza.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Havenza.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
