// <auto-generated />
using Havenza.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Havenza.Infrastructure.Migrations
{
    [DbContext(typeof(HavenzaDbContext))]
    partial class HavenzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Havenza.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Decor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lighting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Textiles"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Living Decor"
                        });
                });

            modelBuilder.Entity("Havenza.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A timeless three-seater sofa with a solid walnut base and linen-blend fabric. Perfect for modern living rooms.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/2.png",
                            Name = "Mid-Century Walnut Sofa",
                            Price = 1299.99m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Compact 4-seater dining table with a genuine white marble top and sleek black metal legs.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/3.png",
                            Name = "Round Marble Dining Table",
                            Price = 749.50m,
                            Stock = 3
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Queen-sized bed with a high, tufted headboard, upholstered in a light beige, durable linen fabric.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/4.png",
                            Name = "Linen Upholstered Bed Frame",
                            Price = 899.00m,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Simple and robust writing desk with two drawers, designed for a clean and focused workspace.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/5.png",
                            Name = "Minimalist Office Desk",
                            Price = 345.99m,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Versatile storage unit with adjustable shelves, finished in a matte dark gray lacquer.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/6.png",
                            Name = "Modular Storage Cabinet",
                            Price = 520.00m,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Large, hand-painted abstract canvas piece with muted blue and warm tan tones.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/7.png",
                            Name = "Abstract Canvas Wall Art",
                            Price = 119.99m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Description = "Full-length standing mirror with a thin, brass-finished curved metal frame.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/8.png",
                            Name = "Curved Metal Floor Mirror",
                            Price = 185.00m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "A collection of five mixed-size frames (3x5, 4x6, 5x7) with natural oak finish and shatter-proof glass. Perfect for creating a gallery wall.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/9.png",
                            Name = "Set of 5 Minimalist Photo Frames",
                            Price = 45.99m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "Silent wall clock featuring an unfinished wood face and simple black hands.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/10.png",
                            Name = "Minimalist Wooden Clock",
                            Price = 59.50m,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Description = "Hand-blown glass vase with a subtle transparent texture, perfect for fresh flowers or as a standalone piece.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/11.png",
                            Name = "Transparent Glass Vase",
                            Price = 35.00m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Single-bulb ceiling pendant with a matte black metal cage design, adjustable cord length.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/12.png",
                            Name = "Industrial Black Pendant Light",
                            Price = 95.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "A classic table lamp featuring a solid brass base and a soft, white linen drum shade.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/13.png",
                            Name = "Brass & Linen Table Lamp",
                            Price = 65.99m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "Tall, arched floor lamp designed to hang over a sofa or chair for optimal reading light.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/14.png",
                            Name = "Arched Reading Floor Lamp",
                            Price = 130.00m,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            Description = "Under-cabinet or shelf-mounted LED light strip for subtle accent illumination.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/15.png",
                            Name = "Minimalist LED Strip Light",
                            Price = 45.00m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Description = "Elegant chandelier with cascading crystal clusters, perfect for dining rooms or entryways.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/16.png",
                            Name = "Crystal Cluster Chandelier",
                            Price = 499.99m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Large area rug made of ethically sourced wool with a subtle geometric pattern in neutral tones.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/17.png",
                            Name = "Hand-Woven Wool Rug (8'x10')",
                            Price = 399.00m,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4,
                            Description = "Ultra-soft acrylic throw blanket with a thick, chunky knit texture, perfect for cozy evenings.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/18.png",
                            Name = "Chunky Knit Throw Blanket",
                            Price = 85.00m,
                            Stock = 22
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            Description = "Pair of luxurious velvet cushion covers (18x18 inches) in a deep forest green.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/19.png",
                            Name = "Set of 2 Velvet Cushion Covers",
                            Price = 29.99m,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4,
                            Description = "Single panel linen curtains with a full blackout lining, 84 inches long.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/20.png",
                            Name = "Blackout Linen Curtains",
                            Price = 55.00m,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4,
                            Description = "Queen size duvet cover and sham set made from ultra-soft 600-thread count Egyptian cotton.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/21.png",
                            Name = "Egyptian Cotton Duvet Cover Set",
                            Price = 110.00m,
                            Stock = 11
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5,
                            Description = "A realistic, high-quality faux fiddle-leaf fig tree (6 ft tall), perfect for low-light spaces.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/22.png",
                            Name = "Large Fiddle-Leaf Fig (Faux)",
                            Price = 159.99m,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5,
                            Description = "Modern white ceramic planter with a geometric diamond texture, suitable for 6-inch plants.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/23.png",
                            Name = "Geometric Ceramic Planter",
                            Price = 29.00m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 5,
                            Description = "Hand-knotted macrame hanger made from natural cotton rope for small to medium pots.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/24.png",
                            Name = "Hanging Macrame Plant Holder",
                            Price = 19.50m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 5,
                            Description = "Low-maintenance succulent gardens in glass terrariums.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/25.png",
                            Name = "Succulent Terrariums",
                            Price = 75.00m,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 5,
                            Description = "Sleek, black powder-coated metal stand, elevating plants to better catch light.",
                            ImageUrl = "Havenza.Web/Havenza.Web/wwwroot/images/products/26.png",
                            Name = "Tall Metal Plant Stand",
                            Price = 49.99m,
                            Stock = 16
                        });
                });

            modelBuilder.Entity("Havenza.Core.Entities.Product", b =>
                {
                    b.HasOne("Havenza.Core.Entities.Category", "CategoryName")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryName");
                });

            modelBuilder.Entity("Havenza.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
